---
- name: Upgrade all packages
  apt: update_cache=yes upgrade=yes
  tags: apt-update
  when: ansible_os_family == "Debian"
  sudo: Yes

- name: Install common packages
  apt: name={{ item }} state=latest
  when: ansible_os_family == "Debian"
  sudo: Yes
  with_items: [ colordiff, curl, git, vim, tmux  ]

- name: Install dotfiles
  command: curl -L sdt.github.io/.dotfiles/install | bash
  args:
    chdir: /home/{{ ansible_ssh_user }}
    creates: /home/{{ ansible_ssh_user }}/.dotfiles
